version: "3.8"

services:
  backend:
    image: pblgllgs/amigos-demo-react-spring:latest
    ports:
      - "80:8080"
    restart: always
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - db


  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_amigos_demo_react_spring:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    networks:
      - db

volumes:
  postgres_amigos_demo_react_spring:
    external: false
networks:
  db: