version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_amigos_demo_react_spring:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: db
    networks:
      - db
volumes:
  postgres_amigos_demo_react_spring:
    external: false
networks:
  db: